class SensorsConfig:
    SENSOR_NAME_KEY = "sensor_name"
    TIMESTAMP_NAME_KEY = "timestamp"

    GYRO_SENSOR_NAME = "gyro"

    GYRO_X_VALUE_NAME = "gyro-x"
    GYRO_Y_VALUE_NAME = "gyro-y"
    GYRO_Z_VALUE_NAME = "gyro-z"

    GYRO_VALUES_UNIT = "rad/s"

    ACCELEROMETER_SENSOR_NAME = "accelerometer"

    ACCELEROMETER_X_VALUE_NAME = "acceleration-x"
    ACCELEROMETER_Y_VALUE_NAME = "acceleration-y"
    ACCELEROMETER_Z_VALUE_NAME = "acceleration-z"

    ACCELEROMETER_VALUES_UNIT = "m/s^2"

    TEMP_SENSOR_NAME = "temperature_sensor"

    TEMP_TEMPERATURE_VALUE_NAME = "temperature"
    TEMP_HUMIDITY_VALUE_NAME = "humidity"

    TEMP_TEMPERATURE_VALUES_UNIT = "°C"
    TEMP_HUMIDITY_VALUES_UNIT = "%"

    CURRENT_SENSOR_NAME = "current_sensor"

    CURRENT_VOLTAGE_VALUE_NAME = "voltage"
    CURRENT_CURRENT_VALUE_NAME = "current"
    CURRENT_POWER_VALUE_NAME = "power"

    CURRENT_VOLTAGE_VALUE_UNIT = "V"
    CURRENT_CURRENT_VALUE_UNIT = "mA"
    CURRENT_POWER_VALUE_UNIT = "mW"

    # Graphs
    GRAPH_TIME = "time"

    GRAPH_ACCELERATION = "acceleration"
    GRAPH_GYRO = "gyro"

    GRAPH_TEMPERATURE = "temperature"
    GRAPH_HUMIDITY = "humidity"

    GRAPH_VOLTAGE = "voltage"
    GRAPH_CURRENT = "current"
    GRAPH_POWER = "power"

    GRAPH_ACCELEROMETER_VALUE = f"{GRAPH_ACCELERATION} ({ACCELEROMETER_VALUES_UNIT})"

    GRAPH_GYRO_VALUE = f"{GRAPH_GYRO} ({GYRO_VALUES_UNIT})"

    GRAPH_TEMP_TEMPERATURE_VALUE = f"temperature ({TEMP_TEMPERATURE_VALUES_UNIT})"
    GRAPH_TEMP_HUMIDITY_VALUE = f"humidity ({TEMP_HUMIDITY_VALUES_UNIT})"

    GRAPH_CURRENT_VOLTAGE_VALUE = f"voltage ({CURRENT_VOLTAGE_VALUE_UNIT})"
    GRAPH_CURRENT_CURRENT_VALUE = f"current ({CURRENT_CURRENT_VALUE_UNIT})"
    GRAPH_CURREBT_POWER_VALUE = f"power ({CURRENT_POWER_VALUE_UNIT})"

    GRAPHS_TITLES = {
        ACCELEROMETER_X_VALUE_NAME: f"{GRAPH_ACCELERATION} x-axis",
        ACCELEROMETER_Y_VALUE_NAME: f"{GRAPH_ACCELERATION} y-axis",
        ACCELEROMETER_Z_VALUE_NAME: f"{GRAPH_ACCELERATION} z-axis",
        GYRO_X_VALUE_NAME: f"{GRAPH_GYRO} x-axis",
        GYRO_Y_VALUE_NAME: f"{GRAPH_GYRO} y-axis",
        GYRO_Z_VALUE_NAME: f"{GRAPH_GYRO} z-axis",
        TEMP_TEMPERATURE_VALUE_NAME: "temperature",
        TEMP_HUMIDITY_VALUE_NAME: "humidity",
        CURRENT_VOLTAGE_VALUE_NAME: "voltage",
        CURRENT_CURRENT_VALUE_NAME: "current",
        CURRENT_POWER_VALUE_NAME: "power"
    }

    GRAPH_AXIS_TITLES = {
        ACCELEROMETER_X_VALUE_NAME: GRAPH_ACCELEROMETER_VALUE,
        ACCELEROMETER_Y_VALUE_NAME: GRAPH_ACCELEROMETER_VALUE,
        ACCELEROMETER_Z_VALUE_NAME: GRAPH_ACCELEROMETER_VALUE,
        GYRO_X_VALUE_NAME: GRAPH_GYRO_VALUE,
        GYRO_Y_VALUE_NAME: GRAPH_GYRO_VALUE,
        GYRO_Z_VALUE_NAME: GRAPH_GYRO_VALUE,
        TEMP_TEMPERATURE_VALUE_NAME: GRAPH_TEMP_TEMPERATURE_VALUE,
        TEMP_HUMIDITY_VALUE_NAME: GRAPH_TEMP_HUMIDITY_VALUE,
        CURRENT_VOLTAGE_VALUE_NAME: GRAPH_CURRENT_VOLTAGE_VALUE,
        CURRENT_CURRENT_VALUE_NAME: GRAPH_CURRENT_CURRENT_VALUE,
        CURRENT_POWER_VALUE_NAME: GRAPH_CURREBT_POWER_VALUE
    }
